services:
    mediabes-proxy:
        build:
            dockerfile: deployment/Proxy.Dockerfile
            context: .
        container_name: mediabes-proxy
        restart: 'no'
        ports:
            - '8000:8000'
    mediabes-frontend:
        build:
            context: .
            dockerfile: deployment/Frontend.Dockerfile
        restart: 'no'
        container_name: mediabes-frontend
        ports:
            - '8001:8000'
    mediabes-backend:
        build:
            context: .
            dockerfile: deployment/Backend.Dockerfile
        restart: 'no'
        container_name: mediabes-backend
        environment:
            DB_HOST: mediabes.mariadb.database.azure.com
            DB_USER: mediabes
            DB_PASSWORD: ${DB_PASSWORD}
            DB_NAME: mediabes
            JWT_SECRET: ${JWT_SECRET}
        ports:
            - '8002:8000'
