name: Test

on:
    push:
        branches:
            - features/deployment
jobs:
    Build:
        runs-on: ubuntu-20.04
        name: BuildAndPushContainer
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                node-version: 'v16.16.0'
                cache: 'npm'

            - name: InstallDependencies
              run: npm install

            - name: Build Project
              run: npm run build:ui

            - name: Upload dist
              uses: actions/upload-artifact@v3
              with:
                name: dist
                path: |
                  dist

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ericaskari
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Frontend Image
              uses: docker/build-push-action@v3
              with:
                context: .
                file: deployment/Frontend.Dockerfile
                push: true
                tags: ericaskari/metropolia-mediabes-frontend

            - name: Build and push Backend Image
              uses: docker/build-push-action@v3
              with:
                context: .
                file: deployment/Backend.Dockerfile
                push: true
                tags: ericaskari/metropolia-mediabes-backend

            - name: Build and push Proxy Image
              uses: docker/build-push-action@v3
              with:
                context: .
                file: deployment/Proxy.Dockerfile
                push: true
                tags: ericaskari/metropolia-mediabes-proxy

    BuildAndPushFrontendContainer:
      name: Build And Push Frontend Container
      needs: Build
      runs-on: ubuntu-20.04
      steps:
        - name: Download Builds
          uses: actions/download-artifact@v3
          with:
            name: dist
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ericaskari
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push Image
          uses: docker/build-push-action@v3
          with:
            context: .
            file: deployment/Frontend.Dockerfile
            push: true
            tags: ericaskari/metropolia-mediabes-frontend

    BuildAndPushBackendContainer:
      name: Build And Push Backend Container
      needs: Build
      runs-on: ubuntu-20.04
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ericaskari
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push Image
          uses: docker/build-push-action@v3
          with:
            context: .
            file: deployment/Backend.Dockerfile
            push: true
            tags: ericaskari/metropolia-mediabes-backend

    BuildAndPushProxyContainer:
      name: Build And Push Proxy Container
      needs: Build
      runs-on: ubuntu-20.04
      steps:
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ericaskari
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push Image
          uses: docker/build-push-action@v3
          with:
            context: .
            file: deployment/Proxy.Dockerfile
            push: true
            tags: ericaskari/metropolia-mediabes-proxy
