name: Test

on:
    push:
        branches:
            - features/deployment
jobs:
    BuildAndPushContainer:
        runs-on: ubuntu-20.04
        name: BuildAndPushContainer
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                node-version: 'v16.16.0'
                cache: 'npm'

            - name: InstallDependencies
              run: npm install

            - name: Build Project
              run: npm run build:ui

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                username: ericaskari
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push Frontend Image
              uses: docker/build-push-action@v3
              with:
                context: .
                file: deployment/Frontend.Dockerfile
                push: true
                tags: ericaskari/metropolia-mediabes-frontend

            - name: Build and push Backend Image
              uses: docker/build-push-action@v3
              with:
                context: .
                file: deployment/Backend.Dockerfile
                push: true
                tags: ericaskari/metropolia-mediabes-backend


            - name: Build and push Proxy Image
              uses: docker/build-push-action@v3
              with:
                context: .
                file: deployment/Proxy.Dockerfile
                push: true
                tags: ericaskari/metropolia-mediabes-proxy

