name: Test

on:
    push:
        branches:
            - features/deployment
jobs:
    BuildAndPushContainer:
        runs-on: ubuntu-20.04
        name: BuildAndPushContainer
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                node-version: 'v16.16.0'
                cache: 'npm'

            - name: InstallDependencies
              run: npm install

            - name: Build Project
              run: npm run build:ui

            - name: Azure CLI script
              uses: azure/CLI@v1
              with:
                azcliversion: 2.30.0
                inlineScript: |
                  az login -u ${{secrets.AZURE_USERNAME}} -p ${{secrets.AZURE_PASSWORD}} show
                  az account show
                  az storage -h
