name: Test

on:
    push:
        branches:
            - main
jobs:
    Test:
        runs-on: ubuntu-20.04
        name: Test
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                node-version: 'v16.16.0'
                cache: 'npm'

            - name: InstallDependencies
              run: npm install

            - name: Build Project
              run: npm run build:ui
